version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            CPU_CORES: "8"
            DISK_SIZE: "500G"
            RAM_SIZE: "4096M"
            ALLOCATE: "N"
            DHCP: "Y"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        volumes:
            - ~/linux_data/appdata/synology_data:/storage
        restart: on-failure
        stop_grace_period: 1m
        networks:
            bridge_macvlan:
                ipv4_address: 192.168.31.139

networks:
  bridge_macvlan:
    driver: macvlan
    driver_opts:
      parent: bridge_eno4
    ipam:
      config:
        - subnet: 192.168.31.0/24
          gateway: 192.168.31.1
          ip_range: 192.168.31.139/24