version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            CPU_CORES: "8"
            DISK_SIZE: "1500G"
            RAM_SIZE: "4096M"
            ALLOCATE: "N"
            DHCP: "Y" # get ip from router, then use router to make it static.
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        volumes:
            - ~/linux_data/appdata/synology_data:/storage
        restart: on-failure
        stop_grace_period: 1m
        networks:
            bridge_macvlan:
                ipv4_address: 192.168.31.139 
                # i dont know why this wont work. 
                # the actual backend ip is still from the router, which is set to 192.168.31.100 for easy access. 
                # I guess that only the ip from the DHCP of the router can be see in the router backend.
                # so I I set 192.168.31.100 here, i can not manage it in the router, which is not good.
                # so I use dynamic IP and use router to make it static

networks:
  bridge_macvlan: # the bridge is from the parent 
    driver: macvlan
    driver_opts:
      parent: bridge_eno4 # ! need to be set outside docker using cockpit
    ipam:
      config:
        - subnet: 192.168.31.0/24
          gateway: 192.168.31.1
          ip_range: 192.168.31.0/24