version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            CPU_CORES: "4"
            DISK_SIZE: "500G"
            RAM_SIZE: "2048M"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN        
        ports:
            - 5000:5000
        volumes:
            - ~/win_data/app_data/synology_data:/storage
        restart: on-failure
        stop_grace_period: 1m
